language: haskell
ghc:
  - 7.8
  - 7.6
install:
  - make install
  - make configure
before_script:
  - git config --global user.email "example@example.com"
  - git config --global user.name "Travis CI"
script:
  - make bench
  - make test
after_script:
  - cabal install hpc-coveralls
  - hpc-coveralls --exclude-dir=test tests examples
